#!/bin/bash

file="$HOME/.config/Xresources"
dir=$HOME/.config/themes
if theme=$(ls $dir | tr " " "\n" | dmenu -l 10 -c -p "Choose Theme: "); then
    sed -i 1d $file && 
    echo "#include \"/home/tony/.config/themes/$theme\"" | cat - $file > temp.txt && 
    mv temp.txt $file && 
    xrdb "$file" &&
    killall dwm &&
    launch_dunst && 
    doom-change-theme $theme && 
    notify-send -u low "Switched Theme To" "$theme" 
fi
