#!/bin/bash

lists=""
drives=$(lsblk -n -i -o name | grep -v -e "sda" -e "sdb" | grep  "sd.[0-9]" | sed 's/`-//g;s/\n/;/g' )

for i in $drives; do
	[ -n "$(lsblk | grep $i | awk '{print $7}')" ] && lists+="$i" && lists+="\n"
done

# if [ "$lists" = "" ]  
# then
# 	notify-send "Nothing to unmount"
# else
# 	mount="$(lsblk -n -i -o name,size,mountpoint | grep $lists | dmenu -i -p "Choose to unmount: ")"
# 	udisksctl unmount -b "/dev/$mount" && notify-send "$mount unmounted"
# fi

 if [ "$lists" = "" ]  
then
	notify-send "Nothing to unmount"
else
	mount="$(echo -e $lists | dmenu -i -p "Choose to unmount: ")"
	udisksctl unmount -b "/dev/$mount" && notify-send "$mount unmounted"
fi
